name: attendance_app
description: Institute Attendance Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.2.0
  
  #web-socket
  web_socket_channel: ^2.4.0  
  
  #serialport
  socket_io_client: ^2.0.3+1 
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # Charts & Visualization
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^24.2.9
  
  # Date & Time
  intl: ^0.19.0
  table_calendar: ^3.0.9
  
  # Loading & Animations
  shimmer: ^3.0.0
  lottie: ^3.0.0
  animated_text_kit: ^4.2.2
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Icons & UI
  feather_icons: ^1.2.0
  flutter_animate: ^4.5.0
  
  # Responsive
  responsive_framework: ^1.4.0
  flutter_screenutil: ^5.9.0
  
  # Utils
  url_launcher: ^6.2.4
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/